version: '3.7'
services:
    cli:
        container_name: node12
        build:
            context: docker/node
            dockerfile: Dockerfile
        volumes:
            - ./:/var/project
        working_dir: /var/project
#        entrypoint: [ "/usr/local/bin/node" ]

    npm:
        container_name: node12-npm
        build:
            context: docker/node
            dockerfile: Dockerfile
        volumes:
            - ./:/var/project
        working_dir: /var/project
        entrypoint: [ "/usr/local/bin/npm" ]

    npx:
        container_name: node12-npx
        build:
            context: docker/node
            dockerfile: Dockerfile
        volumes:
            - ./:/var/project
        working_dir: /var/project
        entrypoint: [ "/usr/local/bin/npx" ]

    ncu:
        container_name: node12-ncu
        build:
            context: docker/node
            dockerfile: Dockerfile
        volumes:
            - ./:/var/project
        working_dir: /var/project
        entrypoint: [ "/usr/local/bin/ncu" ]

    yarn:
        container_name: node12-yarn
        build:
            context: docker/node
            dockerfile: Dockerfile
        volumes:
            - ./:/var/project
        working_dir: /var/project
        entrypoint: [ "/usr/local/bin/yarn" ]

    gulp:
        container_name: node12-gulp
        build:
            context: docker/node
            dockerfile: Dockerfile
        volumes:
            - ./:/var/project
        working_dir: /var/project
        entrypoint: ['/usr/local/bin/gulp']

    eslint:
        container_name: node12-eslint
        build:
            context: docker/node
            dockerfile: Dockerfile
        volumes:
            - ./:/var/project
        working_dir: /var/project
        entrypoint: ['/usr/local/bin/eslint']