version: '3.7'
services:
  node:
    container_name: node10
    build: 
      context: docker/node
      dockerfile: Dockerfile
    volumes:
      - ./:/var/project
      - "./docker/.volumes/npm:/root/.npm:delegated"
    working_dir: /var/project

  gulp:
    container_name: node10-gulp
    build: 
      context: docker/node
      dockerfile: Dockerfile
    volumes:
      - ./:/var/project
      - "./docker/.volumes/npm:/root/.npm:delegated"
    working_dir: /var/project
    entrypoint: ['/usr/local/bin/gulp', '-f', './gulp.js']