version: '3.7'
services:
  node:
    container_name: node12
    build:
      context: docker/node
      dockerfile: Dockerfile
    volumes:
      - "./:/var/project:delegated"
      - "./node_modules:/var/project/node_modules:cached"
    working_dir: /var/project

  gulp:
    container_name: node12-gulp
    build:
      context: docker/node
      dockerfile: Dockerfile
    volumes:
      - "./:/var/project:delegated"
    working_dir: /var/project
    entrypoint: ['/usr/local/bin/gulp', '-f', './gulp.js']
