export PATH="./docker/bin:../docker/bin:../../docker/bin:$PATH"
export PROJECT_ROOT="$PWD"

alias _build="docker-compose build --force-rm --pull"
alias _ps="docker-compose ps"
alias _run="docker-compose run --rm"
alias _stop="docker-compose stop"
alias _up="docker-compose up --detach --force-recreate --remove-orphans"
alias no-start="docker-compose up --no-start --force-recreate --remove-orphans"
alias _mysql="mysql --host=127.0.0.1 --user=root --default-character-set=utf8mb4"

alias eslint="docker-compose run --rm cli eslint"
alias gulp="docker-compose run --rm gulp"
alias hadolint="docker-compose run --rm hadolint"
alias node="docker-compose run --rm cli"
alias npm="docker-compose run --rm cli npm"
alias npx="docker-compose run --rm cli npx"
alias yarn="docker-compose run --rm yarn"