alias node="docker-compose run --rm cli"
alias npm="docker-compose run --rm npm"
alias npx="docker-compose run --rm npx"
alias yarn="docker-compose run --rm yarn"
alias gulp="docker-compose run --rm gulp"
alias eslint="docker-compose run --rm eslint"
alias hadolint="docker-compose run --rm hadolint"