FROM node:13-alpine

RUN apk --no-cache add \
    curl \
    git \
    groff

RUN npm install -g \
    npm@latest \
    npm-check-updates \
    eslint \
    gulp \
    typescript \
    webpack \
    webpack-cli