name: Docker Image CI

on:
  create:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
      - name: Build the Docker image
        run: |
          echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          echo ${{ secrets.PACKAGE_TOKEN }} | docker login docker.pkg.github.com -u tommyheavenly7 --password-stdin
          docker build --pull -t docker.pkg.github.com/tommyheavenly7/docker-node/node10:${{ steps.vars.outputs.tag }} ./export/node10/
          docker push docker.pkg.github.com/tommyheavenly7/docker-node/node10:${{ steps.vars.outputs.tag }}
          docker build --pull -t docker.pkg.github.com/tommyheavenly7/docker-node/node10:latest ./export/node10/
          docker push docker.pkg.github.com/tommyheavenly7/docker-node/node10:latest
          docker build --pull -t docker.pkg.github.com/tommyheavenly7/docker-node/node12:${{ steps.vars.outputs.tag }} ./export/node12/
          docker push docker.pkg.github.com/tommyheavenly7/docker-node/node12:${{ steps.vars.outputs.tag }}
          docker build --pull -t docker.pkg.github.com/tommyheavenly7/docker-node/node12:latest ./export/node12/
          docker push docker.pkg.github.com/tommyheavenly7/docker-node/node12:latest
          docker build --pull -t docker.pkg.github.com/tommyheavenly7/docker-node/node13:${{ steps.vars.outputs.tag }} ./export/node13/
          docker push docker.pkg.github.com/tommyheavenly7/docker-node/node13:${{ steps.vars.outputs.tag }}
          docker build --pull -t docker.pkg.github.com/tommyheavenly7/docker-node/node13:latest ./export/node13/
          docker push docker.pkg.github.com/tommyheavenly7/docker-node/node13:latest
          docker build --pull -t docker.pkg.github.com/tommyheavenly7/docker-node/node14:${{ steps.vars.outputs.tag }} ./export/node14/
          docker push docker.pkg.github.com/tommyheavenly7/docker-node/node14:${{ steps.vars.outputs.tag }}
          docker build --pull -t docker.pkg.github.com/tommyheavenly7/docker-node/node14:latest ./export/node14/
          docker push docker.pkg.github.com/tommyheavenly7/docker-node/node14:latest
